// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bktssrqjxhotlfqzuewg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdHNzcnFqeGhvdGxmcXp1ZXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjA4MzMsImV4cCI6MjA1OTA5NjgzM30.iUfRn-ojNPcutBlCkz78qDVKtVCtbdT3wlmh9sfoUqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);